fn main() {

    print(123);
    try {
        a := new int[3];
        a[3];
        throw new Exception("xxs");
    } catch NameError? as e {

    }
}